services:
  - type: static
    name: upay-ngo-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true

  - type: web
    name: upay-ngo-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
